name: Build and deploy JAR app to Azure Web App - PlanYourTrip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven (with tests env)
        working-directory: Backend/TripAI_Backend
        env:
          DUFFEL_API_KEY: ${{ secrets.DUFFEL_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DUFFEL_API_BASE_URL: ${{ secrets.DUFFEL_API_BASE_URL }}
          GEMINI_API_BASE_URL: ${{ secrets.GEMINI_API_BASE_URL }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: Backend/TripAI_Backend/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0F4D6C3D89B048AEBA9C02B6DED7C6B8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_80B1B436223D41149C414B523353AA97 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DFC9B853C5D8466D9B0B255797CCC398 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PlanYourTrip'
          slot-name: 'Production'
          package: '*.jar'
